@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

start
 :User enters add appointment command;
 if (missing parameters?) then (yes)
    : CogniCare throws a Parse Exception;
    : Error message is displayed;
 else (no)
    if (all parameters entered correctly?) then (yes)
            :Create a new appointment object;
            :Return a new AddAppointmentCommand;
            if (new appointment is valid?) then (yes)
                :Appointment is added to CogniCare;
                :Success message is displayed;
            else (no)
                :CogniCare throws a Command Exception;
                :Error message is displayed;
            endif
        else (no)
            : CogniCare throws a Parse Exception;
            : Error message is displayed;
        endif
 endif
stop

@enduml
