@startuml

start
 :User enters add appointment command;
 if () then ([else] )
    : CogniCare throws a Parse Exception;
    : Error message is displayed;

 else ( [is valid command format] )

    if () then ([else] )
        : CogniCare throws a Parse Exception;
        : Error message is displayed;

    else ( [prefix(es) are valid])
        :Create a new appointment object;
        :Return a new AddAppointmentCommand;

        if () then ([else] )
            :CogniCare throws a Command Exception;
            :Error message is displayed;

        else ( [new appointment is valid])
            :Appointment is added to CogniCare;
            :Success message is displayed;
        endif

    endif

 endif
stop

@enduml
