@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class MainApp #grey
    Class MainWindow #grey
    Class Parser LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1

MainApp -[#grey]-> UI
UI -right[#grey]-> MainWindow
UI -down[#green]-> Logic

Storage -[STORAGE_COLOR].> Model
Storage .right[STORAGE_COLOR].>File

' Command .right[LOGIC_COLOR_T2]-> Model
Parser -right[LOGIC_COLOR_T2]-> Model

Logic -down[#blue]-> Model
Logic -right[#blue]-> Storage
Logic -down[#blue]-> Parser

User ..> MainApp
@enduml
