@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deletep 1")
activate LogicManager

LogicManager -> CommandParser : parseCommand("deletep 1")
activate CommandParser

create DeleteCommandParser
CommandParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> CommandParser
deactivate DeleteCommandParser

CommandParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser :
deactivate DeleteCommand

DeleteCommandParser --> CommandParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> CommandParser
destroy DeleteCommandParser

CommandParser --> LogicManager : d
deactivate CommandParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

DeleteCommand -> Model : getFilteredPersonList()
activate Model
DeleteCommand -> Model : getFilteredAppointmentList()
DeleteCommand -> Model : getIdTracker()
Model --> DeleteCommand: current running ID
DeleteCommand -> Model : deletePerson(1)
Model --> DeleteCommand: Optional.of(personToDelete)
DeleteCommand -> Model : deleteAppointment()
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
