@startuml
!include style.puml
skinparam ArrowFontStyle plain

box DeletePatientSequenceDiagram LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":DeletePatientCommandParser" as DeletePatientCommandParser LOGIC_COLOR
participant ":DeletePatientCommand" as DeletePatientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(args)
activate LogicManager

LogicManager -> CommandParser : parseCommand(args)
activate CommandParser

create DeletePatientCommandParser
CommandParser -> DeletePatientCommandParser
activate DeletePatientCommandParser

DeletePatientCommandParser --> CommandParser
deactivate DeletePatientCommandParser

CommandParser -> DeletePatientCommandParser : parse(args)
activate DeletePatientCommandParser

create DeletePatientCommand
DeletePatientCommandParser -> DeletePatientCommand
activate DeletePatientCommand

DeletePatientCommand --> DeletePatientCommandParser :
deactivate DeletePatientCommand

DeletePatientCommandParser --> CommandParser
deactivate DeletePatientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeletePatientCommandParser -[hidden]-> CommandParser
destroy DeletePatientCommandParser
DeletePatientCommandParser -[hidden]-> CommandParser

CommandParser --> LogicManager : command
deactivate CommandParser

LogicManager -> DeletePatientCommand : execute(model)
activate DeletePatientCommand


DeletePatientCommand -> Model : deletePerson()
activate Model
Model --> DeletePatientCommand
deactivate Model


DeletePatientCommand -> Model : delete appointments related to person
activate Model
deactivate Model
create CommandResult
DeletePatientCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePatientCommand
deactivate CommandResult

DeletePatientCommand --> LogicManager : result
deactivate DeletePatientCommand

[<--LogicManager
deactivate LogicManager
@enduml
