@startuml

start
 :User enters the delete appointment command;
 if () then ([else] )

    : Return new DeleteAppointmentCommand;
            if () then ([else] )
                : CogniCare throws a Command Exception;
                : Error message is displayed;

            else ( [valid index])

                if () then ([else] )
                    : CogniCare throws a Command Exception;
                    : Error message is displayed;
                else ( [appointment is present])
                    : CogniCare deletes the appointment;
                    : Success message is displayed;
                endif

            endif

 else ( [missing appointment index])
    : CogniCare throws a Parse Exception;
    : Error message is displayed;

 endif
stop
@enduml
