@startuml

:User enters query command;
if () then ([else] )
    :CogniCare throws a Parse Exception;
    :Error message is displayed;

else ( [no duplicate parameters])
    if () then ([else] )
        :CogniCare throws a Parse Exception;
        :Error message is displayed;
    else ( [is valid command format])
        if () then([else] )
            if() then([else] )
                :CogniCare throws a Parse Exception;
                :Error message is displayed;
            else( [preamble is empty])
                :Return all appointments;
            endif
        else( [prefix(es) are specified])
            if () then([else] )
                :CogniCare throws a Parse Exception;
                :Error message is displayed;
            else( [prefix(es) are valid])
                :Filter list by prefix(es);
                :Return filtered appointments;
            endif
        endif
    endif
endif
stop

@enduml
