@startuml
!include style.puml
skinparam ArrowFontStyle plain

box ReportFeedbackCommand LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":ReportFeedbackCommandParser" as ReportFeedbackCommandParser LOGIC_COLOR
' participant ":FilterAppointmentPredicate" as FilterAppointmentPredicate LOGIC_COLOR
participant ":ReportFeedbackCommand" as ReportFeedbackCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":PatientReportFeedbackList" as PatientReportFeedbackList LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(args)
activate LogicManager
LogicManager -> CommandParser : parseCommand(args)
activate CommandParser

create ReportFeedbackCommandParser
CommandParser -> ReportFeedbackCommandParser
activate ReportFeedbackCommandParser

ReportFeedbackCommandParser --> CommandParser
deactivate ReportFeedbackCommandParser
CommandParser -> ReportFeedbackCommandParser : parse(args)
activate ReportFeedbackCommandParser

create ReportFeedbackCommand
ReportFeedbackCommandParser -> ReportFeedbackCommand
activate ReportFeedbackCommand
ReportFeedbackCommand --> ReportFeedbackCommandParser
deactivate ReportFeedbackCommand

ReportFeedbackCommandParser --> CommandParser
deactivate ReportFeedbackCommandParser
ReportFeedbackCommandParser -[hidden]-> CommandParser
destroy ReportFeedbackCommandParser

CommandParser --> LogicManager: command
deactivate CommandParser
LogicManager -> ReportFeedbackCommand : execute(model)

activate ReportFeedbackCommand
ReportFeedbackCommand -> Model: filter appointment list
activate Model
Model -> PatientReportFeedbackList: generate report list
activate PatientReportFeedbackList
deactivate PatientReportFeedbackList
Model --> ReportFeedbackCommand
deactivate Model
create CommandResult
ReportFeedbackCommand -> CommandResult
activate CommandResult
CommandResult --> ReportFeedbackCommand
deactivate CommandResult

ReportFeedbackCommand --> LogicManager: result
deactivate ReportFeedbackCommand
' destroy ReportFeedbackCommand
[<-- LogicManager : return filtered patient\n feedback reports
@enduml
