@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "PatientList Storage" #F4F6F6{
Class "<<interface>>\nPatientListStorage" as PatientListStorage
Class JsonPatientListStorage
Class JsonSerializablePatientList
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "AppointmentList Storage" #F4F6F6{
Class "<<interface>>\nAppointmentListStorage" as AppointmentListStorage
Class JsonSerializableAppointmentList
Class JsonAdaptedAppointment
Class JsonAppointmentListStorage
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -down-> "1" UserPrefsStorage
StorageManager -left-> "1" PatientListStorage
StorageManager -right-> "1" AppointmentListStorage

Storage --|> UserPrefsStorage
Storage --|> PatientListStorage
Storage --|> AppointmentListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPatientListStorage .up.|> PatientListStorage
JsonPatientListStorage ..> JsonSerializablePatientList
JsonSerializablePatientList --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonAppointmentListStorage .up.|> AppointmentListStorage
JsonAppointmentListStorage ..> JsonSerializableAppointmentList
JsonSerializableAppointmentList --> "*" JsonAdaptedAppointment
@enduml