@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

start
 :User enters the delete appointment command;
 if (missing appointment index?) then ([no])

    : Return new DeleteAppointmentCommand;
            if (is valid index?) then ([no])
                : CogniCare throws a Command Exception;
                : Error message is displayed;

            else ([yes])

                if (appointment is present) then ([no])
                    : CogniCare throws a Command Exception;
                    : Error message is displayed;
                else ([yes])
                    : CogniCare deletes the appointment;
                    : Success message is displayed;
                endif

            endif

 else ([yes])
    : CogniCare throws a Parse Exception;
    : Error message is displayed;

 endif
stop
@enduml
