@startuml
!include style.puml
skinparam ArrowFontStyle plain

box EditPatientSequenceDiagram LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":EditPatientCommandParser" as EditPatientCommandParser LOGIC_COLOR
participant ":EditPersonDescriptor" as EditPersonDescriptor LOGIC_COLOR
participant ":EditPatientCommand" as EditPatientCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(args)
activate LogicManager

LogicManager -> CommandParser : parseCommand(args)
activate CommandParser

create EditPatientCommandParser
CommandParser -> EditPatientCommandParser
activate EditPatientCommandParser

EditPatientCommandParser --> CommandParser
deactivate EditPatientCommandParser

CommandParser -> EditPatientCommandParser : parse(args)
activate EditPatientCommandParser

create EditPersonDescriptor
note right of EditPersonDescriptor : Methods in EditPersonDescriptor such as setName and\n setPhone may be used to create a defensive copy \nof the patient that is to be updated.
EditPatientCommandParser -> EditPersonDescriptor
activate EditPersonDescriptor
EditPersonDescriptor -> EditPatientCommandParser

deactivate EditPersonDescriptor

' Now, passing EditPersonDescriptor and studentIndex to EditPatientCommand
create EditPatientCommand
EditPatientCommandParser -> EditPatientCommand
activate EditPatientCommand
EditPatientCommand --> EditPatientCommandParser
deactivate EditPatientCommand

EditPatientCommandParser --> CommandParser : return
deactivate EditPatientCommandParser
EditPatientCommandParser -[hidden]-> CommandParser
destroy EditPatientCommandParser

CommandParser --> LogicManager : d
deactivate CommandParser

LogicManager -> EditPatientCommand : execute(model)
activate EditPatientCommand

EditPatientCommand -> Model : updateFilteredPersonList
activate Model

Model --> EditPatientCommand
deactivate Model

EditPatientCommand --> LogicManager : return updated patient list
deactivate EditPatientCommand

[<--LogicManager : command successful
deactivate LogicManager
@enduml
