@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant ":ListPatientCommandParser" as ListPatientCommandParser LOGIC_COLOR
participant ":ListCommandPatient" as ListCommandPatient LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("queryp" + " n/Jerome p/123 e/gmail.com a/depression")
activate LogicManager

LogicManager -> CommandParser : parseCommand("queryp" + arguments)
activate CommandParser

create ListPatientCommandParser
CommandParser -> ListPatientCommandParser
activate ListPatientCommandParser

ListPatientCommandParser --> CommandParser
deactivate ListPatientCommandParser

CommandParser -> ListPatientCommandParser : parse(arguments)
activate ListPatientCommandParser

create ListCommandPatient
ListPatientCommandParser -> ListCommandPatient :  new ListCommandPatient(combinedPredicate) with AND logic
note right of ListPatientCommandParser : Details of how predicates are combined \nare simplified for the sake of diagramming.
activate ListCommandPatient

ListCommandPatient --> ListPatientCommandParser :
deactivate ListCommandPatient

ListPatientCommandParser --> CommandParser : d
deactivate ListPatientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListPatientCommandParser -[hidden]-> CommandParser
destroy ListPatientCommandParser

CommandParser --> LogicManager : d
deactivate CommandParser

LogicManager -> ListCommandPatient : execute(m)
activate ListCommandPatient

ListCommandPatient -> Model : updateFilteredPersonList(combinedPredicate)
activate Model

Model --> ListCommandPatient
deactivate Model




ListCommandPatient --> LogicManager : command success
deactivate ListCommandPatient

[<--LogicManager : command successful
deactivate LogicManager
@enduml
