@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR

participant ":CommandParser" as CommandParser LOGIC_COLOR
participant "h:HelpCommand" as HelpCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager: execute(args)
activate LogicManager
LogicManager -> CommandParser: parse(args)

activate CommandParser
create HelpCommand
CommandParser -> HelpCommand: HelpCommand()
activate HelpCommand
HelpCommand --> CommandParser
deactivate HelpCommand
LogicManager <-- CommandParser: h
deactivate CommandParser
LogicManager -> HelpCommand: execute(model)
activate HelpCommand
create CommandResult
HelpCommand -> CommandResult: CommandResult()
activate CommandResult
CommandResult --> HelpCommand
deactivate CommandResult
HelpCommand --> LogicManager
deactivate HelpCommand

[<- LogicManager: Execute Command in GUI
deactivate LogicManager
@enduml
